//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCSampleProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Account
    {
        public int UserID { get; set; }

        [Required]
        [StringLength(50, MinimumLength = 6)]
        [DisplayName("Your username")]
        public string UserName { get; set; }

        [Required]
        [DisplayName("Password")]
        public string UserPassword { get; set; }

        [NotMapped]
        [Required]
        [DisplayName("Confirm your password")]
        [System.ComponentModel.DataAnnotations.Compare("UserPassword")]
        public string ConfirmPassword { get; set; }

        [DisplayName("Your role")]
        public string UserRole { get; set; }
    }
}
